#pragma once

#include <windows.h>
#include <d3d11.h>
#include <dxgi1_2.h>
#include <d3d10umddi.h>
#include <wchar.h>

#define WDM_SEAN_DOS_NAME TEXT("\\\\.\\VIDPN_SEAN")
#define VIDPN_SEAN_CTRL_DEV_TYPE FILE_DEVICE_UNKNOWN
#define VIDPN_SEAN_FUNC_CODE 0x800

#define IOCTRL_VIDPN_SEAN_ECHOTEST \
    CTL_CODE( VIDPN_SEAN_CTRL_DEV_TYPE, VIDPN_SEAN_FUNC_CODE+1, METHOD_BUFFERED , FILE_ANY_ACCESS  )

#define IOCTRL_VIDPN_SEAN_ADDVIDPNPATH \
	CTL_CODE( VIDPN_SEAN_CTRL_DEV_TYPE, VIDPN_SEAN_FUNC_CODE+2, METHOD_BUFFERED , FILE_ANY_ACCESS  )

#define IOCTRL_VIDPN_SEAN_SETPOWER \
	CTL_CODE( VIDPN_SEAN_CTRL_DEV_TYPE, VIDPN_SEAN_FUNC_CODE+3, METHOD_BUFFERED , FILE_ANY_ACCESS  )

#define IOCTRL_VIDPN_SEAN_SETCHILDUID \
	CTL_CODE( VIDPN_SEAN_CTRL_DEV_TYPE, VIDPN_SEAN_FUNC_CODE+4, METHOD_BUFFERED , FILE_ANY_ACCESS  )

#define IOCTRL_WDM_SEAN_MONITORCTRL \
	CTL_CODE( VIDPN_SEAN_CTRL_DEV_TYPE, VIDPN_SEAN_FUNC_CODE+5, METHOD_BUFFERED , FILE_ANY_ACCESS  )

#define IOCTRL_WDM_SEAN_INSPECT_VIDPN \
	CTL_CODE( VIDPN_SEAN_CTRL_DEV_TYPE, VIDPN_SEAN_FUNC_CODE+6, METHOD_BUFFERED , FILE_ANY_ACCESS  )

#define IOCTRL_VIDPN_SEAN_DEACTIVE \
	CTL_CODE( VIDPN_SEAN_CTRL_DEV_TYPE, VIDPN_SEAN_FUNC_CODE+7, METHOD_BUFFERED , FILE_ANY_ACCESS  )

#define IOCTRL_VIDPN_SEAN_NEWPATH \
	CTL_CODE( VIDPN_SEAN_CTRL_DEV_TYPE, VIDPN_SEAN_FUNC_CODE+8, METHOD_BUFFERED , FILE_ANY_ACCESS  )

#define IOCTRL_VIDPN_SEAN_SET_PRIMARY_ALLOCATION \
	CTL_CODE( VIDPN_SEAN_CTRL_DEV_TYPE, VIDPN_SEAN_FUNC_CODE+9, METHOD_BUFFERED , FILE_ANY_ACCESS  )
